import { conflict, type Failure } from '@kompass/core';

/**
 * Grund und Abhilfe je Fehlerschlüssel (Finanz-Spec 5.4: „Fehlerbilder sind
 * `Result`-Werte mit Grund **und** Abhilfe“). Eine Tabelle statt verstreuter
 * Texte, damit ein Test sie vollständig halten kann und F3 sie unverändert in
 * die Sprachdatei übernimmt. `financeConflict` ist die einzige Stelle im Modul,
 * die einen `conflict(…)` erzeugt (Wächter: `tests/errors.test.ts`).
 */
export const FINANCE_ERRORS = {
  accountInUse: { reason: 'Auf dieses Konto ist bereits gebucht.', remedy: 'Das Konto lässt sich stilllegen, aber nicht löschen.' },
  mainAccountMustBeBank: { reason: 'Das Hauptkonto kann nur ein Bankkonto sein.', remedy: 'Seine IBAN steht auf den Zuwendungsbestätigungen — wählen Sie ein Bankkonto.' },
  mainAccountMustStayActive: { reason: 'Das Hauptkonto lässt sich nicht stilllegen oder löschen.', remedy: 'Machen Sie zuerst ein anderes Konto zum Hauptkonto.' },
  categoryKeyTaken: { reason: 'Der Schlüssel {key} ist bereits vergeben.', remedy: 'Wählen Sie einen anderen Schlüssel.' },
  categoryInUse: { reason: 'Auf diese Kategorie ist bereits gebucht.', remedy: 'Die Kategorie lässt sich stilllegen, aber nicht löschen.' },
  purposeInUse: { reason: 'Auf diesen Zweck ist bereits gebucht.', remedy: 'Der Zweck lässt sich stilllegen, aber nicht löschen.' },
  purposeClosed: { reason: 'Der Zweck ist erfüllt oder aufgelöst.', remedy: 'Öffnen Sie ihn wieder, bevor Sie ihn ändern.' },
  fiscalYearExists: { reason: 'Es gibt bereits ein Geschäftsjahr.', remedy: 'Legen Sie weitere Geschäftsjahre über die Buchung an.' },
  designationLocked: { reason: 'Die Bezeichnung steht bereits in vergebenen Buchungsnummern.', remedy: 'Sie ist damit unveränderlich; legen Sie bei Bedarf ein neues Geschäftsjahr an.' },
  designationTaken: { reason: 'Die Bezeichnung {designation} ist bereits vergeben.', remedy: 'Wählen Sie eine andere Bezeichnung für das Geschäftsjahr.' },
  entryNotDraft: { reason: 'Buchung {number} ist festgeschrieben.', remedy: 'Festgeschriebenes wird nicht geändert: Nehmen Sie die Buchung zurück und legen Sie eine neue an.' },
  entryNotFinal: { reason: 'Die Buchung ist noch ein Entwurf.', remedy: 'Ein Entwurf wird gelöscht, nicht zurückgenommen.' },
  entryUnbalanced: { reason: 'Es sind noch {rest} zu verteilen: Die Konten ergeben {money}, die Zuordnungen {allocated}.', remedy: 'Ergänzen oder ändern Sie eine Aufteilung, bis beide Summen gleich sind.' },
  entryEmpty: { reason: 'Die Buchung hat keine Zeilen.', remedy: 'Fügen Sie mindestens ein Konto oder ein Zuordnungspaar hinzu.' },
  accountInactive: { reason: 'Das Konto {account} ist stillgelegt.', remedy: 'Wählen Sie ein aktives Konto oder aktivieren Sie es unter „Finanzen einrichten“.' },
  categoryInactive: { reason: 'Die Kategorie {category} ist stillgelegt.', remedy: 'Wählen Sie eine aktive Kategorie oder aktivieren Sie sie unter „Finanzen einrichten“.' },
  fiscalYearClosed: { reason: 'Das Geschäftsjahr {year} ist abgeschlossen.', remedy: 'Buchen Sie im laufenden Jahr, oder öffnen Sie das Jahr wieder (Recht „Geschäftsjahr abschließen”).' },
  noFiscalYearForDate: { reason: 'Für den {date} gibt es noch kein Geschäftsjahr.', remedy: 'Ein Geschäftsjahr anlegen kann {names}.' },
  cashDraftNotAllowed: { reason: 'Bargeld wird am selben Tag festgehalten; ein Entwurf auf einem Barkonto lässt sich nicht parken.', remedy: 'Buchen Sie den Vorgang in einem Zug (festschreiben beim Speichern).' },
  cashWouldGoNegative: { reason: 'Das Barkonto {account} wäre am {date} mit {amount} im Minus.', remedy: 'Prüfen Sie Datum und Betrag, oder buchen Sie zuerst die fehlende Einnahme oder Abhebung.' },
  cashNegativeNeedsReason: { reason: 'Durch diese Rücknahme wäre das Barkonto {account} am {date} mit {amount} im Minus.', remedy: 'Geben Sie eine Begründung an; der Zeitraum steht dann im Prüfpaket.' },
  entryAlreadyReversed: { reason: 'Buchung {number} ist schon zurückgenommen (durch {by}).', remedy: 'Nichts zu tun.' },
  entryIsReversal: { reason: 'Buchung {number} ist selbst eine Rücknahme.', remedy: 'Eine Rücknahme wird nicht zurückgenommen: Legen Sie die Buchung neu an.' },
  entryLocked: { reason: 'Buchung {number} lässt sich nicht zurücknehmen: {reason}', remedy: 'Lösen Sie zuerst, was darauf aufbaut.' },
  notReviewed: { reason: '{count} der gewählten Entwürfe sind nicht geprüft.', remedy: 'Der Sammellauf nimmt nur geprüfte Entwürfe: Prüfen Sie sie zuerst, oder schreiben Sie sie einzeln fest.' },
  noTaxRateForDate: { reason: 'Für den {date} ist kein Umsatzsteuersatz hinterlegt.', remedy: 'Tragen Sie den Satz unter „Finanzen einrichten → Werte“ mit seinem Stichtag ein.' },
  voucherTypeNotAllowed: { reason: 'Die Art „{type}“ gilt beim Verein nicht als Finanzbeleg.', remedy: 'Wählen Sie eine der hinterlegten Belegarten, oder tragen Sie die Art unter „Finanzen einrichten“ nach.' },
  documentNotFinal: { reason: 'Das Dokument ist noch ein Entwurf.', remedy: 'Ein Beleg braucht ein festgeschriebenes Dokument der Akte.' },
  documentVoided: { reason: 'Das Dokument ist widerrufen.', remedy: 'Verknüpfen Sie ein gültiges Dokument als Beleg.' },
  voucherAlreadyLinked: { reason: 'Dieses Dokument hängt schon als Beleg an der Buchung.', remedy: 'Verknüpfen Sie es nicht ein zweites Mal.' },
  voucherAlreadyRevoked: { reason: 'Dieser Beleg ist bereits widerrufen.', remedy: 'Ein Widerruf lässt sich nicht wiederholen.' },
  revokeNeedsReplacement: { reason: 'Das Geschäftsjahr {year} ist abgeschlossen.', remedy: 'Widerrufen Sie den Beleg, indem Sie ihn ersetzen: Geben Sie das richtige Dokument mit an.' },
  settlementExceedsLine: { reason: 'Die Summe der Zuordnungen übersteigt den Betrag des Kontos.', remedy: 'Verringern Sie eine Zuordnung, oder teilen Sie die Zahlung auf mehrere Zeilen auf.' },
  settlementWrongDirection: { reason: 'Eine Verbindlichkeit wird durch eine Ausgabe beglichen, eine Forderung durch eine Einnahme.', remedy: 'Prüfen Sie das Vorzeichen des Kontos oder wählen Sie den passenden Posten.' },
  openItemCancelled: { reason: 'Der Posten ist ohne Zahlung erledigt.', remedy: 'Wählen Sie einen offenen Posten, oder legen Sie einen neuen an.' },
  openItemInUse: { reason: 'Auf diesen Posten ist bereits eine Zahlung zugeordnet.', remedy: 'Ein zugeordneter Posten lässt sich nicht mehr ändern.' },
  openItemHasPayments: { reason: 'Auf diesen Posten ist bereits eine festgeschriebene Zahlung zugeordnet.', remedy: 'Stornieren Sie zuerst die Zahlung, bevor Sie den Posten ohne Zahlung erledigen.' },
  openItemHasOrigin: { reason: 'Dieser Posten hat eine Herkunft.', remedy: 'Er wird über seinen Vorgang erledigt.' },
  lineNotFinal: { reason: 'Die Zeile gehört zu einem Entwurf.', remedy: 'Ändern Sie den Entwurf direkt — eine Korrektur ist nur für festgeschriebene Zeilen.' },
  correctionChangesNothing: { reason: 'Keines der angegebenen Felder weicht vom aktuellen Wert ab.', remedy: 'Geben Sie mindestens eine tatsächliche Änderung an.' },
  purposeChangeNeedsProof: { reason: 'Der Zweck einer Einnahmezeile ändert sich nur mit einem Dokument, das die ursprüngliche Bestimmung des Spenders belegt.', remedy: 'Legen Sie ein festgeschriebenes Dokument als Nachweis mit an, oder buchen Sie eine Umwidmung.' },
  ownCorrection: { reason: 'Eine Korrektur gibt nicht frei, wer sie angelegt hat.', remedy: 'Lassen Sie eine andere Person mit dem Recht „Freigeben“ die Korrektur bestätigen.' },
  section153Unacknowledged: { reason: 'Für das Geschäftsjahr ist die Steuererklärung bereits abgegeben — die Änderung berührt § 153 AO.', remedy: 'Bestätigen Sie den Hinweis, um fortzufahren.' },
  contactLocked: { reason: 'Der Kontakt ist gesperrt: {reason}', remedy: 'Lösen Sie zuerst, was die Sperre begründet.' },
  correctionNotPending: { reason: 'Die Korrektur wartet nicht mehr auf eine Entscheidung.', remedy: 'Legen Sie bei Bedarf eine neue Korrektur an.' },
  correctionPendingExists: { reason: 'Für diese Zeile wartet schon eine Korrektur auf Freigabe.', remedy: 'Entscheiden Sie zuerst über die wartende Korrektur.' },
  draftsInPeriod: { reason: 'Im Geschäftsjahr stehen noch {count} Entwürfe.', remedy: 'Schreiben Sie sie fest oder löschen Sie sie.' },
  undocumentedEntries: { reason: 'Im Geschäftsjahr stehen {count} Buchungen ohne Beleg.', remedy: 'Reichen Sie den Beleg nach, legen Sie einen Eigenbeleg an, oder begründen Sie, warum es keinen gibt.' },
  previousYearOpen: { reason: 'Das Vorjahr ist noch nicht abgeschlossen.', remedy: 'Geschäftsjahre schließen in ihrer Reihenfolge: Schließen Sie zuerst das Vorjahr.' },
  fiscalYearAlreadyClosed: { reason: 'Das Geschäftsjahr {year} ist bereits abgeschlossen.', remedy: 'Öffnen Sie es bei Bedarf wieder (Recht „Geschäftsjahr abschließen“).' },
  fiscalYearNotEnded: { reason: 'Das Geschäftsjahr {year} ist noch nicht zu Ende.', remedy: 'Ein Geschäftsjahr lässt sich frühestens nach seinem Enddatum abschließen.' },
  fiscalYearNotClosed: { reason: 'Das Geschäftsjahr {year} ist nicht abgeschlossen.', remedy: 'Nur ein abgeschlossenes Geschäftsjahr lässt sich wieder öffnen.' },
  laterYearClosed: { reason: 'Ein späteres Geschäftsjahr ist bereits abgeschlossen.', remedy: 'Öffnen Sie zuerst das spätere Geschäftsjahr wieder — Jahre öffnen in umgekehrter Reihenfolge.' },
  cashCountNeedsNote: { reason: 'Bei einem Fehlbetrag ist ein Satz zur Erklärung Pflicht.', remedy: 'Tragen Sie ein, was fehlt oder wo der Betrag geblieben ist.' },
  cashCountSameCounter: { reason: 'Die beiden Zählenden müssen unterschiedliche Personen sein.', remedy: 'Wählen Sie eine zweite Person.' },
  cashCountCounterNotPerson: { reason: 'Zählende sind Personen, keine Organisationen.', remedy: 'Wählen Sie einen Kontakt der Art Person.' },
  cashCountNotCash: { reason: 'Das Konto {account} ist kein Barkonto.', remedy: 'Zählen lässt sich nur eine Kasse oder Spendendose.' },
  cashCountInFuture: { reason: 'Das Zähldatum liegt in der Zukunft.', remedy: 'Wählen Sie den heutigen Tag oder einen vergangenen.' },
  cashMoveNeedsOneCash: { reason: 'Eine Bargeldbewegung braucht genau ein Barkonto — das andere ist ein Bankkonto.', remedy: 'Wählen Sie ein Bankkonto und ein Barkonto.' },
  switchUiOnly: { reason: 'Dieser Schalter lässt sich nur am Bildschirm ändern.', remedy: 'Melden Sie sich an und ändern Sie ihn dort.' },
  // F4 Task 3 — der Lauf.
  statementAccountNotBank: { reason: 'Ein Kontoauszug lässt sich nur für ein Bankkonto oder einen Zahlungsdienst laden.', remedy: 'Wählen Sie ein passendes Konto.' },
  statementTooLarge: { reason: 'Die Datei ist größer als das eingestellte Limit von {limit} MB.', remedy: 'Prüfen Sie die Datei, oder erhöhen Sie das Limit unter „Finanzen einrichten“.' },
  statementUnreadable: { reason: 'Der Auszug lässt sich nicht lesen{location}.', remedy: 'Prüfen Sie die Datei, oder laden Sie den Auszug erneut aus dem Online-Banking herunter.' },
  statementIbanMismatch: { reason: 'Die IBAN im Auszug passt nicht zum Konto {account}.', remedy: 'Wählen Sie das passende Konto, oder tragen Sie die richtige IBAN am Konto ein.' },
  statementFormatChange: { reason: 'Für {account} war bisher ein anderes Auszugsformat hinterlegt; nach dem Wechsel gibt es mehr Zweifelsfälle.', remedy: 'Bestätigen Sie den Wechsel, wenn Sie ihn wirklich wollen.' },
  // F4b — ein CSV-Format entsteht nur über den Assistenten (bzw. `saveImportProfile`), nie als bloßes Feld am Konto.
  accountCsvNeedsFormat: { reason: 'Ein Konto liest CSV erst, wenn sein CSV-Format eingerichtet ist.', remedy: 'Richten Sie das CSV-Format unter „Hochgeladene Auszüge“ mit dem Assistenten ein.' },
  statementNeedsCsvFormat: { reason: 'Für {account} ist noch kein CSV-Format eingerichtet.', remedy: 'Richten Sie das CSV-Format einmal ein — der Assistent rät zuerst, ob Ihre Bank CAMT anbietet.' },
  statementCsvFormatMismatch: { reason: 'Die Datei passt nicht zum CSV-Format von {account} ({format}).', remedy: 'Laden Sie den Auszug im gewohnten Format, oder richten Sie ein neues Format ein — das ist ein Formatwechsel.' },
  statementAlreadyImported: { reason: 'Dieser Auszug wurde für das Konto {account} bereits geladen.', remedy: 'Nichts zu tun — oder verwerfen Sie den vorhandenen Auszug zuerst, wenn er falsch war.' },
  // N3 (W-1) — das Konto erkennt Kompass am Auszug; eine CAMT-Datei gehört dafür zu genau einem Konto.
  statementMultipleAccounts: { reason: 'Die Datei enthält Auszüge für mehrere Konten ({ibans}). Kompass liest je Datei ein Konto.', remedy: 'In der Banking-App je Konto eine Datei exportieren und die Dateien einzeln laden.' },
  // N2 — Kontostand nachtragen (genau einmal, Trigger finance_import_runs_balance_once).
  runHasBalance: { reason: 'Dieser hochgeladene Auszug hat schon einen Kontostand.', remedy: 'Stimmt er nicht, verwerfen Sie den Auszug und laden Sie ihn mit dem richtigen Kontostand neu.' },
  runNotAmendable: { reason: 'Nur ein fertig geladener, nicht verworfener Auszug bekommt einen Kontostand.', remedy: 'Laden Sie den Auszug zuerst vollständig — ein verworfener Auszug bekommt seinen Kontostand über einen neuen, richtigen Auszug.' },
  // F4 Task 4 — Kandidaten entscheiden, Rohumsatz an der Geldzeile.
  rawTransactionMismatch: { reason: 'Der gewählte Kontoumsatz passt nicht zu Konto, Vorzeichen oder Betrag dieser Zeile.', remedy: 'Wählen Sie den passenden Kontoumsatz, oder lösen Sie die Verknüpfung.' },
  rawTransactionTaken: { reason: 'Dieser Kontoumsatz ist bereits einer anderen Buchung zugeordnet.', remedy: 'Wählen Sie einen anderen Kontoumsatz, oder nehmen Sie zuerst die vorhandene Buchung zurück.' },
  rawTransactionDiscarded: { reason: 'Der Auszug, aus dem dieser Kontoumsatz stammt, wurde verworfen.', remedy: 'Laden Sie den Auszug bei Bedarf erneut, oder lösen Sie die Verknüpfung.' },
  candidateAlreadyDecided: { reason: 'Für diesen Kontoumsatz-Kandidaten steht die Entscheidung schon fest.', remedy: 'Nichts zu tun.' },
  // F4 Task 5 — Auszug verwerfen.
  statementNotDiscardable: { reason: 'Dieser hochgeladene Auszug lässt sich nicht verwerfen.', remedy: 'Nur ein fertig geladener, noch nicht verworfener Auszug lässt sich verwerfen.' },
  statementDiscardBlocked: { reason: 'Für diesen hochgeladenen Auszug gibt es noch festgeschriebene Buchungen.', remedy: 'Nehmen Sie die Buchungen zurück, dann lässt sich der Auszug verwerfen.' },
  // F5 — Arbeitsliste, Regeln, Kontakt über IBAN.
  ruleNeedsCondition: { reason: 'Eine Regel braucht mindestens eine Bedingung.', remedy: 'Wählen Sie Konto, Richtung, IBAN, einen Textteil oder einen Betragsbereich — sonst träfe die Regel jeden Kontoumsatz.' },
  ruleCategoryInactive: { reason: 'Die Regel „{name}“ bucht auf eine stillgelegte Kategorie.', remedy: 'Aktivieren Sie die Kategorie unter „Finanzen einrichten“, oder ändern Sie die Regel.' },
  suggestionStale: { reason: 'Der Kontoumsatz ist inzwischen zugeordnet.', remedy: 'Laden Sie die Liste neu — der Vorschlag gilt nicht mehr.' },
  transactionAlreadyBooked: { reason: 'Dieser Kontoumsatz gehört schon zu einer Buchung.', remedy: 'Öffnen Sie die Buchung, oder nehmen Sie sie zurück, wenn sie falsch ist.' },
  entryLineNotBindable: { reason: 'Diese Buchung hat keine passende Zeile auf diesem Konto ohne Kontoumsatz.', remedy: 'Wählen Sie eine Buchung mit demselben Konto und Betrag, oder buchen Sie den Kontoumsatz neu.' },
  foreignNeedsHolder: { reason: 'Sagen Sie, für wen das Geld ist.', remedy: 'Tragen Sie ein, wem das Geld gehört — der Satz steht im Buchungstext.' },
  contactIbanTaken: { reason: 'Diese IBAN gehört bereits zum Kontakt {contact}.', remedy: 'Lösen Sie zuerst die vorhandene Zuordnung, wenn die IBAN jetzt jemand anderem gehört.' },
  voucherSearchNeedsRead: { reason: 'Die Suche nach Belegen braucht das Recht, Finanzen mit Namen zu lesen.', remedy: 'Bitten Sie eine Person mit dem Recht „Finanzen lesen“, den Beleg zuzuordnen.' },
  // F5b — Rechnungen mit ZUGFeRD/Factur-X.
  openItemExistsForDocument: { reason: 'Zu dieser Rechnung gibt es schon eine offene Zahlung.', remedy: 'Öffnen Sie die vorhandene offene Zahlung, statt eine zweite anzulegen.' },
  invoiceCurrencyUnsupported: { reason: 'Die Rechnung lautet auf {currency}, Kompass übernimmt nur Rechnungen in Euro.', remedy: 'Buchen Sie sie von Hand, mit dem Betrag, der vom Konto abging.' },
  invoiceToolsMissing: { reason: 'Die Anhänge des PDFs lassen sich hier nicht lesen, weil die Texterkennung nicht eingerichtet ist.', remedy: 'Richten Sie die Texterkennung ein (poppler-utils mit pdfdetach), siehe Handbuch docs/handbuch/betrieb.md — bis dahin buchen Sie die Rechnung von Hand.' },
  invoiceNotDraft: { reason: 'Die Angaben einer Rechnung lassen sich nur in einen Entwurf übernehmen.', remedy: 'Wählen Sie einen Entwurf, oder nehmen Sie die festgeschriebene Buchung zurück und buchen Sie neu.' },
  invoiceUnreadable: { reason: 'Der Rechnungsanhang des PDFs ist keine lesbare ZUGFeRD-Rechnung ({code}).', remedy: 'Buchen Sie die Rechnung von Hand; die Angaben stehen im PDF selbst.' },
  // F6a — Bescheide und Zuwendungsbestätigungen. Die Bescheidarten heißen hier nie mit ihrem Namen aus dem Steuerrecht (Verbotsliste der Oberfläche).
  noticeVoided: { reason: 'Dieser Bescheid ist als irrtümlich erfasst gekennzeichnet.', remedy: 'Erfassen Sie den richtigen Bescheid neu.' },
  noticeSuperseded: { reason: 'Dieser Bescheid ist aufgehoben oder ersetzt.', remedy: 'Ein ersetzter Bescheid bleibt, wie er ist — erfassen Sie den neuen Bescheid.' },
  noticeNotValidAt: { reason: 'Der gewählte Bescheid gilt am {date} nicht.', remedy: 'Prüfen Sie das Datum, oder erfassen Sie den Bescheid, der an diesem Tag galt.' },
  noNoticeValidAt: { reason: 'Am {date} gilt kein Bescheid des Finanzamts — ohne Bescheid keine Zuwendungsbestätigung.', remedy: 'Erfassen Sie den Bescheid unter Spenden → Bescheide.' },
  noticeAfterExemption: { reason: 'Es gibt schon einen endgültigen Bescheid vom {date}; eine vorläufige Feststellung danach gibt es nicht.', remedy: 'Erfassen Sie stattdessen den neuen endgültigen Bescheid des Finanzamts.' },
  confirmationLineNotFinal: { reason: 'Die Zuwendung gehört zu einer Buchung, die noch nicht festgeschrieben ist.', remedy: 'Schreiben Sie die Buchung zuerst fest.' },
  confirmationLineReversed: { reason: 'Die Buchung dieser Zuwendung ist zurückgenommen.', remedy: 'Bestätigen Sie die neue Buchung, falls es eine gibt.' },
  confirmationIncomeNotCertifiable: { reason: 'Für die Kategorie „{category}“ gibt es keine Zuwendungsbestätigung.', remedy: 'Bestätigt werden nur Geldspenden, Mitgliedsbeiträge, Sachspenden und Aufwandsspenden — korrigieren Sie die Kategorie, wenn sie falsch ist.' },
  confirmationContactIncomplete: { reason: 'Name oder Anschrift des Empfängers sind unvollständig.', remedy: 'Ergänzen Sie Name, Straße, Postleitzahl und Ort am Kontakt.' },
  confirmationOrganizationIncomplete: { reason: 'Name oder Anschrift des Vereins fehlen in den Vereinsdaten.', remedy: 'Ergänzen Sie Name, Straße, Postleitzahl und Ort unter Verwaltung → Stammdaten.' },
  confirmationLineAlreadyConfirmed: { reason: 'Für diese Zuwendung gibt es schon die Bestätigung {number}.', remedy: 'Nehmen Sie diese zuerst zurück, wenn eine neue nötig ist.' },
  confirmationAmountNotPositive: { reason: 'Nach Rückbuchungen bleibt von dieser Zuwendung kein Betrag übrig.', remedy: 'Es gibt nichts zu bestätigen.' },
  confirmationEntryUndocumented: { reason: 'Zu dieser Zuwendung fehlt der Beleg.', remedy: 'Reichen Sie den Beleg zur Buchung nach, dann lässt sich die Bestätigung ausstellen.' },
  confirmationInKindDetailsMissing: { reason: 'Zur Sachspende fehlen Angaben: Gegenstand, Zustand, Wertermittlung oder Herkunft.', remedy: 'Beschreiben Sie die Sachspende, bevor Sie die Bestätigung ausstellen.' },
  confirmationInKindMixed: { reason: 'Sachspenden und Geldzuwendungen stehen nie auf derselben Bestätigung.', remedy: 'Stellen Sie für die Sachspende eine eigene Bestätigung aus.' },
  confirmationTypeInactive: { reason: 'Die Dokumentart für Zuwendungsbestätigungen ist stillgelegt.', remedy: 'Aktivieren Sie sie in der Akte unter „Dokumentarten“.' },
  confirmationExpenseWaiversDisabled: { reason: 'Aufwandsspenden sind ausgeschaltet.', remedy: 'Schalten Sie sie unter „Finanzen einrichten → Steuerliches“ ein, wenn der Verein sie bestätigt.' },
  confirmationBeforeExemptionStart: { reason: 'Die Zuwendung vom {entryDate} liegt vor dem Beginn der Steuerbefreiung am {exemptFrom}; dafür darf keine Bestätigung ausgestellt werden.', remedy: 'Prüfen Sie unter Spenden → Bescheide, ab wann der Bescheid die Befreiung ausspricht.' },
  confirmationAlreadyVoided: { reason: 'Diese Bestätigung ist bereits zurückgenommen.', remedy: 'Nichts zu tun.' },
  confirmationAlreadySent: { reason: 'Der Versand dieser Bestätigung ist schon vermerkt.', remedy: 'Ein Versandvermerk lässt sich nicht überschreiben.' },
  confirmationChangedMeanwhile: { reason: 'Während des Ausstellens hat sich an der Zuwendung, am Bescheid oder am Unterzeichner etwas geändert.', remedy: 'Prüfen Sie die Angaben und stellen Sie die Bestätigung erneut aus.' },
  confirmationSignedAlready: { reason: 'Die unterschriebene Fassung ist schon abgelegt.', remedy: 'Nichts zu tun — die abgelegte Fassung bleibt.' },
  signerOverlaps: { reason: 'Der Zeitraum überschneidet sich mit einem anderen Unterzeichner.', remedy: 'Beenden Sie zuerst den Zeitraum des bisherigen Unterzeichners.' },
  facsimileTooLarge: { reason: 'Das Bild der Unterschrift ist größer als 1 MB.', remedy: 'Verkleinern Sie das Bild und laden Sie es erneut hoch.' },
  facsimileNotImage: { reason: 'Die Datei ist kein PNG- oder JPEG-Bild.', remedy: 'Laden Sie die Unterschrift als PNG oder JPEG hoch.' },
  entryLockedByConfirmation: { reason: 'Auf dieser Buchung liegt die Bestätigung {number}.', remedy: 'Nehmen Sie zuerst die Bestätigung zurück, dann die Buchung.' },
  contactLockedByConfirmation: { reason: 'Der Kontakt dieser Zeile steht in der Bestätigung {number}.', remedy: 'Nehmen Sie zuerst die Bestätigung zurück, korrigieren Sie dann und stellen Sie neu aus.' },
  inKindLineOnly: { reason: 'Angaben zur Sachspende gehören nur an eine Zeile der Art Sachspende.', remedy: 'Wählen Sie die Zeile mit der Sachspende, oder korrigieren Sie die Kategorie.' },
  // F6b — Serienlauf, Sammel-PDFs, Versandvermerk für alle.
  runNothingToIssue: { reason: 'In diesem Jahr gibt es nichts zu bestätigen.', remedy: 'Prüfen Sie Jahr, Mindestbetrag und ausgeschlossene Kontakte — oder alle Zuwendungen sind schon bestätigt.' },
  runAlreadyFinished: { reason: 'Dieser Serienlauf ist schon abgeschlossen.', remedy: 'Starten Sie einen Nachzügler-Lauf, wenn noch Zuwendungen fehlen.' },
  runBlocked: { reason: 'Der Serienlauf kann nicht starten: {reason}', remedy: 'Beheben Sie das zuerst, dann rechnet die Vorschau neu.' },
  runItemNotPending: { reason: 'Dieser Posten des Serienlaufs ist schon erledigt.', remedy: 'Laden Sie die Seite neu — ein anderer Aufruf war schneller.' },
  bundleToolsMissing: { reason: 'Die Sammel-PDFs lassen sich hier nicht zusammenfügen, weil das Werkzeug dafür fehlt.', remedy: 'Richten Sie poppler-utils mit pdfunite ein, siehe Handbuch docs/handbuch/betrieb.md — die einzelnen Bestätigungen stehen trotzdem in der Akte.' },
  bundleEmpty: { reason: 'In diesem Teil des Serienlaufs gibt es keine ausgestellte Bestätigung.', remedy: 'Warten Sie, bis der Lauf Bestätigungen ausgestellt hat, oder wählen Sie den anderen Teil.' },
  dispatchNothingMachine: { reason: 'In diesem Serienlauf gibt es keine maschinelle Bestätigung ohne Versandvermerk.', remedy: 'Zu unterschreibende Bestätigungen bekommen den Vermerk erst, wenn die unterschriebene Fassung abgelegt ist.' },
  // F8a — Auslagen: einreichen, freigeben, Verzicht (Spec 8.2).
  expenseNeedsContactLink: { reason: 'Ihr Nutzerkonto ist mit keinem Kontakt verknüpft — ohne ihn weiß Kompass nicht, wem die Auslage erstattet wird.', remedy: 'Verknüpfen Sie Ihr Nutzerkonto einmal selbst mit Ihrem Kontakt, oder bitten Sie darum: {names}.' },
  expenseNotDraft: { reason: 'Dieser Antrag ist schon eingereicht.', remedy: 'Ein eingereichter Antrag bleibt, wie er ist — nach einer Ablehnung reichen Sie ihn neu ein.' },
  expenseNotSubmitted: { reason: 'Dieser Antrag wartet nicht mehr auf Freigabe.', remedy: 'Laden Sie die Seite neu — vermutlich hat ihn gerade jemand anderes freigegeben oder abgelehnt.' },
  expenseNothingToSubmit: { reason: 'Der Antrag hat noch keine Position.', remedy: 'Fügen Sie mindestens einen Beleg oder eine Fahrt hinzu.' },
  expensePositionNeedsReceipt: { reason: 'Position {position} fehlt noch der Beleg.', remedy: 'Wählen Sie das PDF für Position {position}, oder behalten Sie den Antrag als Entwurf.' },
  expenseTripNeedsKm: { reason: 'Eine Fahrt braucht Kilometer, einen Anlass und einen Betrag über 0.', remedy: 'Tragen Sie Kilometer und Anlass der Fahrt ein.' },
  expenseIbanOrWaiver: { reason: 'Es fehlt die IBAN, auf die erstattet wird.', remedy: 'Tragen Sie eine gültige IBAN ein — oder verzichten Sie auf die Erstattung, wenn der Verein das anbietet.' },
  expenseOwnClaim: { reason: 'Sie haben diesen Antrag selbst angelegt.', remedy: 'Den eigenen Antrag gibt immer jemand anderes frei. Das kann erledigen: {names}.' },
  expenseSameContact: { reason: 'Sie sind die antragstellende Person.', remedy: 'Den eigenen Antrag gibt immer jemand anderes frei. Das kann erledigen: {names}.' },
  expenseCategoryRequired: { reason: 'Position {position} hat noch keine Kategorie.', remedy: 'Wählen Sie für jede Position eine Ausgabe-Kategorie, dann lässt sich freigeben.' },
  expenseWaiversDisabled: { reason: 'Aufwandsspenden sind beim Verein ausgeschaltet.', remedy: 'Reichen Sie den Antrag ohne Verzicht neu ein, oder schalten Sie Aufwandsspenden unter „Finanzen einrichten“ ein.' },
  waiverAgreedAfterPosition: { reason: 'Die Vereinbarung über den Erstattungsanspruch ist jünger als die früheste Position.', remedy: 'Ein Verzicht setzt einen vorher vereinbarten Anspruch voraus — begründen Sie die Abweichung, oder zahlen Sie die Auslage aus.' },
  waiverLateNeedsReason: { reason: 'Der Verzicht kommt nach Ablauf der Frist.', remedy: 'Geben Sie eine Begründung an; sie steht am Antrag.' },
  waiverFundsInsufficient: { reason: 'Am {date} hatte der Verein nur {free} frei verfügbar — weniger als die {amount} des Antrags.', remedy: 'Ein Verzicht setzt voraus, dass der Verein hätte zahlen können: Zahlen Sie die Auslage aus, statt den Verzicht anzunehmen.' },
  waiverDeclarationMissing: { reason: 'Die Verzichtserklärung liegt noch nicht vor.', remedy: 'Erzeugen Sie die Verzichtserklärung und verknüpfen Sie sie mit dem Antrag.' },
  waiverNotConfirmed: { reason: 'Es ist nicht bestätigt, dass der Anspruch vorab vereinbart war.', remedy: 'Prüfen Sie die Vereinbarung und setzen Sie das Häkchen „Anspruch vorab vereinbart“.' },
  expenseFileNotPdf: { reason: 'Die Datei {file} ist kein PDF.', remedy: 'Wählen Sie ein PDF — Ihre Eingaben bleiben stehen.' },
  expenseFileTooLarge: { reason: 'Die Datei {file} ist größer als {limit}.', remedy: 'Wählen Sie eine kleinere Datei — Ihre Eingaben bleiben stehen.' },
  expenseNotOwner: { reason: 'Dieser Antrag gehört einer anderen Person.', remedy: 'Sie sehen und ändern nur Ihre eigenen Anträge.' },
  waiverSignedAlready: { reason: 'Die unterschriebene Verzichtserklärung liegt schon am Antrag.', remedy: 'Sie wird nur einmal abgelegt — die abgelegte Fassung finden Sie am Antrag.' },
  expenseWaiverCategoryMissing: { reason: 'Es gibt keine aktive Kategorie für Aufwandsspenden.', remedy: 'Legen Sie unter „Finanzen einrichten“ eine Einnahme-Kategorie der Art „Aufwandsspende“ an oder aktivieren Sie sie wieder.' },
  expenseNotRejected: { reason: 'Neu einreichen lässt sich nur ein abgelehnter Antrag.', remedy: 'Warten Sie die Entscheidung ab — ein Entwurf lässt sich weiter bearbeiten, ein eingereichter wird freigegeben oder abgelehnt.' },
  batchNothingReviewed: { reason: 'Es gibt keine geprüften Entwürfe zum Festschreiben.', remedy: 'Prüfen Sie zuerst Entwürfe in der Arbeitsliste, dann lassen sie sich gemeinsam festschreiben.' },
} as const satisfies Record<string, { reason: string; remedy: string }>;

export type FinanceErrorCode = keyof typeof FINANCE_ERRORS;

function fill(template: string, params: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in params ? String(params[key]) : match));
}

/** `conflict(code, "<Grund> <Abhilfe>")`; `{platzhalter}` in beiden Texten werden aus `params` ersetzt. */
export function financeConflict(code: FinanceErrorCode, params?: Record<string, string | number>): Failure {
  const { reason, remedy } = FINANCE_ERRORS[code];
  return conflict(code, `${fill(reason, params)} ${fill(remedy, params)}`);
}
