import type { McpToolDefinition } from '@kompass/core';
import { z } from 'zod';
import { animalCreateSchema, animalDeleteSchema, animalDeletionPreview, animalListSchema, animalPhotosSchema, animalReviewRequestSchema, animalStatusSchema, animalStorySchema, animalUpdateSchema, createAnimal, deleteAnimal, getAnimal, listAnimals, MAX_ANIMAL_PHOTOS, requestAnimalReview, setAnimalPhotos, setAnimalPublished, setAnimalStatus, setAnimalStory, updateAnimal } from './service';

const t = (name: string, description: string, inputSchema: z.ZodType<unknown>, handler: McpToolDefinition['handler'], service: McpToolDefinition['service']): McpToolDefinition => ({ name, description, inputSchema, handler, service });

export const ANIMALS_MCP_TOOLS: McpToolDefinition[] = [
  t('animals_list', 'List animals as short rows without texts: id, slug, name, status, location, flags, publication, review marker, photo count. Optional filters: text (name or slug contains), status, location, isPublished, reviewPending; orderBy { field: name | createdAt | updatedAt | reviewRequestedAt, direction }. Returns { animals, total, reviewPending }; the two counters are unfiltered. For texts, photos and story of one animal use animals_get. Requires animals.view.', animalListSchema, (deps, ctx, args) => listAnimals(deps, ctx, args), listAnimals),
  t('animals_get', 'Read one animal profile with photos, story and review marker (reviewRequestedAt, reviewNote). Requires animals.view.', z.object({ id: z.string() }), (deps, ctx, args) => getAnimal(deps, ctx, (args as { id: string }).id), getAnimal),
  t('animals_create', 'Create an animal profile (unpublished). Requires animals.manage. place: free text, not localized, e.g. shelter country or town, or the federal state of a foster home. Writing through MCP marks the profile for review by a human; add what to check with animals_request_review.', animalCreateSchema, (deps, ctx, args) => createAnimal(deps, ctx, args), createAnimal),
  t('animals_update', 'Update an animal profile. Requires animals.manage. Localized fields are replaced as a whole map; to change one locale use translations_set. Pass expectedVersion (the updatedAt you last read) to be rejected with staleVersion instead of overwriting a change made in between. place: free text, not localized, e.g. shelter country or town, or the federal state of a foster home. Writing through MCP marks the profile for review by a human; add what to check with animals_request_review.', animalUpdateSchema, (deps, ctx, args) => updateAnimal(deps, ctx, args), updateAnimal),
  t('animals_set_status', 'Change adoption status of an animal. Requires animals.manage.', animalStatusSchema, (deps, ctx, args) => setAnimalStatus(deps, ctx, args), setAnimalStatus),
  t('animals_set_photos', `Replace photo gallery of an animal, at most ${MAX_ANIMAL_PHOTOS} photos. Requires animals.manage. Writing through MCP marks the profile for review by a human; add what to check with animals_request_review.`, animalPhotosSchema, (deps, ctx, args) => setAnimalPhotos(deps, ctx, args), setAnimalPhotos),
  t('animals_set_story', 'Set adoption success story of an adopted animal. Requires animals.manage. Localized fields are replaced as a whole map; to change one locale use translations_set. Pass expectedVersion (the updatedAt you last read) to be rejected with staleVersion instead of overwriting a change made in between. Writing through MCP marks the profile for review by a human; add what to check with animals_request_review.', animalStorySchema, (deps, ctx, args) => setAnimalStory(deps, ctx, args), setAnimalStory),
  t('animals_request_review', 'Mark an animal profile for review by a human and say what to check in note (max 500 characters, no personal data). Use it after changing a profile, or when nothing changed but a human should look (e.g. no longer listed at the partner). Only a human can confirm the review, in the web interface. Requires animals.manage.', animalReviewRequestSchema, (deps, ctx, args) => requestAnimalReview(deps, ctx, args), requestAnimalReview),
  t('animals_set_published', 'Publish or unpublish an animal profile. Requires animals.manage.', z.object({ id: z.string(), isPublished: z.boolean() }), (deps, ctx, args) => setAnimalPublished(deps, ctx, args), setAnimalPublished),
  t('animals_deletion_preview', 'Tell whether an animal profile can be deleted: still published, held by retention, still referenced (documents, open follow-ups), and which photos are used nowhere else. Call this before animals_delete. Requires animals.view.', z.object({ id: z.string() }), (deps, ctx, args) => animalDeletionPreview(deps, ctx, (args as { id: string }).id), animalDeletionPreview),
  t('animals_delete', 'Delete an animal profile with its photo assignments and success story (editorial content, audited). Two steps: a published profile must be unpublished first. Refused while a retention hold runs or a document or open follow-up still points at it. deleteOrphanedMedia also deletes the photos used nowhere else and needs media.upload. Requires animals.manage.', animalDeleteSchema, (deps, ctx, args) => deleteAnimal(deps, ctx, args), deleteAnimal),
];
