export const CORE_VERSION = '0.1.0';

export * from './result';
export * from './concurrency';
export * from './clock';
export { newId, ID_PATTERN } from './ids';
export * from './context';
export type { AppEnv, Deps } from './deps';
export { validate } from './validate';
export * from './deletion-policy';
export * from './deletion-guards';
export * as schema from './db/schema';
export type { Db, DbOrTx } from './db/client';
export { openDatabase, runMigrations } from './db/client';
export * from './permissions/core';
export * from './permissions/check';
export * from './permissions/human';
export * from './modules/manifest';
export * from './modules/registry';
export * from './modules/service';
export * from './modules/provisions';
export * from './modules/installs';
export * from './modules/record-hooks';
export * from './modules/document-areas';
export * from './modules/linked-access';
export { coreModule } from './core-module';
export * from './audit/log';
export * from './audit/query';
export * from './files/reset';
export * from './files/store';
export * from './media/service';
export * from './media/references';
export * from './media/folders';
export * from './media/preview';
export * from './documents/service';
export * from './documents/engine';
export * from './backup';
export * from './settings/service';
export { CORE_SETTINGS } from './settings/core';
export * from './auth/password';
export * from './auth/sessions';
export * from './auth/login';
export * from './auth/tokens';
export * from './roles/service';
export * from './roles/provision';
export * from './roles/effective';
export * from './users/service';
export * from './themes/tokens';
export * from './themes/default-theme';
export * from './themes/contrast';
export * from './themes/service';
export * from './published/view';
export * from './published/organization';
export * from './setup/service';
export * from './app';
export * from './help/handbook';
export * from './seed/seed';
export * from './i18n/locales';
export * from './i18n/localized';
export * from './i18n/service';
export * from './i18n/paths';
export * from './i18n/translations';
export { localizedColumn } from './db/columns';
export * from './retention/classes';
export * from './retention/service';
export * from './follow-ups/service';
export * from './follow-ups/targets';
export * from './dashboard/types';
export * from './dashboard/service';
export * from './dashboard/tiles';
export * from './users/names';
export * from './text/extraction';
